version: '3.5'

services:
  app:
    container_name: flaskapp
    build:
      context: .
      # dockerfile: app/Dockerfile
    env_file:
      - env_file
    expose:
      - 8080
    depends_on:
      - database

  database:
    container_name: postgres
    image: postgres:11
    env_file: db/database.conf
    ports:
      - 5432:5432  
    volumes:
      - db_volume:/var/lib/postgresql

volumes:
  db_volume: