version: '3.5'

services:
  app:
    container_name: flaskapp
    build:
      context: .
      # dockerfile: app/Dockerfile
    env_file:
      - env_file
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - db_nw
      - web_nw
      
  db:
    container_name: postgres
    image: postgres:11
    ports:
      - 5432:5432  
    env_file:
      - env_file
    volumes:
      - db_volume:/var/lib/postgresql
    networks:
      - db_nw
  nginx:
    image: "nginx:1.13.5"
    ports:
      - "8080:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - web_nw
    depends_on: 
      - app
networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge
volumes:
  db_volume: