version: '3.5'

services:
  app:
    container_name: flaskapp
    build:
      context: .
      # dockerfile: app/Dockerfile
    expose:
      - 8080
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:11
    ports:
      - 5432:5432  
    volumes:
      - db_volume:/var/lib/postgresql

volumes:
  db_volume: